#######################################################################################
# Autogit - config and deploy hooks                                                   #
#######################################################################################

branch: pixel-positions

shared_files: [ .env ]
shared_folders: [ storage, bootstrap/cache ]

hooks:
  # SETUP: Create folder structure for newest release
  setup_before: |
    exit 0
  setup_after: |
    exit 0

  # INSTALL: Put code in release folder
  install_before: |
    exit 0
  install_after: |

    # Install PHP dependencies
    composer install --optimize-autoloader --no-interaction

    # Install and build frontend assets
    npm ci
    npm run build

    # Set correct permissions
    chmod -R 775 storage bootstrap/cache

    exit 0

  # SHAREDSYMLINK: Create symlink to shared files and folders
  sharedsymlink_before: |
    exit 0
  sharedsymlink_after: |
    exit 0

  # SYMLINK: Set current symlink to newest release
  symlink_before: |
    exit 0
  symlink_after: |
    # Clear config FIRST (removes cached config pointing to SQLite)
    php artisan config:clear

    # NOW clear cache (will read fresh .env)
    php artisan cache:clear
    php artisan view:clear

    # Run Laravel post-deploy commands

    php artisan migrate --force
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    php artisan storage:link

    exit 0

  # CLEANUP: Cleanup old releases, two most recent releases remaining
  cleanup_before: |
    exit 0
  cleanup_after: |
    exit 0
